export const PLATFORM_ROLES = ["PLATFORM_SUPER_ADMIN"] as const;

export const ORGANIZATION_ROLES = [
  "ORGANIZATION_ADMIN",
  "HR_ADMIN",
  "MANAGER",
  "EMPLOYEE",
  "PAYROLL_OFFICER",
  "RECRUITER",
] as const;

export const PERMISSIONS = [
  "platform.organization.delete",
  "platform.organization.create",
  "platform.organization.read",
  "platform.organization.update",
  "platform.organization.suspend",
  "organization.settings.manage",
  "organization.admin.invite",
  "organization.employee.invite",
  "organization.role.assign",
  "employee.read",
  "employee.create",
  "employee.update",
  "department.read",
  "department.create",
  "department.update",
  "department.delete",
  "designation.read",
  "designation.create",
  "designation.update",
  "designation.delete",
  "leave.request",
  "leave.approve",
  "attendance.manage",
  "payroll.read_own",
  "payroll.process",
] as const;

export const ROLE_PERMISSIONS: Record<string, readonly string[]> = {
  PLATFORM_SUPER_ADMIN: [
    "platform.organization.create",
    "platform.organization.read",
    "platform.organization.update",
    "platform.organization.suspend",
    "platform.organization.delete",
  ],
  ORGANIZATION_ADMIN: [
    "organization.settings.manage",
    "organization.admin.invite",
    "organization.employee.invite",
    "organization.role.assign",
    "employee.read",
    "employee.create",
    "employee.update",
    "department.read",
    "department.create",
    "department.update",
    "department.delete",
    "designation.read",
    "designation.create",
    "designation.update",
    "designation.delete",
    "leave.request",
    "leave.approve",
    "attendance.manage",
    "payroll.read_own",
    "payroll.process",
  ],
  HR_ADMIN: [
    "organization.employee.invite",
    "employee.read",
    "employee.create",
    "employee.update",
    "department.read",
    "department.create",
    "department.update",
    "department.delete",
    "designation.read",
    "designation.create",
    "designation.update",
    "designation.delete",
    "leave.approve",
    "attendance.manage",
  ],
  MANAGER: ["employee.read", "department.read", "designation.read", "leave.request", "leave.approve"],
  EMPLOYEE: ["leave.request", "payroll.read_own", "department.read", "designation.read"],
  PAYROLL_OFFICER: ["employee.read", "department.read", "designation.read", "payroll.read_own", "payroll.process"],
  RECRUITER: ["employee.read", "department.read", "designation.read"],
};

